### PR TITLE
Adding Athletic Robot (Accepted) 🎉

### PR DESCRIPTION
**Pull request by saschasalles**

### CODE REVIEW

**Review by thisIsTheFoxe — CHANGES_REQUESTED** [review]
Congrats! 🎉 
Please use your real name for the _Name_ column. Also, please note the top Readme comments that we limit Technologies to max. 4 entries. 
Thanks :)

**Comment by saschasalles** [comment]
@thisIsTheFoxe Oh sorry, now it's should be okay :)

**Comment by thisIsTheFoxe** [comment]
@saschasalles thanks, the entry looks good. 
However, I'm sorry for the inconvenience but it looks like we ran into some conflicts as we started merging other entires. Please resolve them while keeping the alphabetical order.
Thanks again :)

**Comment by saschasalles** [comment]
Now it should be good, @thisIsTheFoxe , sorry again :D

**Review by thisIsTheFoxe — APPROVED** [review]
Haha no problem at all. Thanks for fixing it ^-^
Also, I see the newline you added on top.. 👀 but that's fine :D 
Congrats again! 🎉 lgtm 👍

**Pull request merged**
