### PR TITLE
Added BlinkBoard (Accepted!)

### PR DESCRIPTION
**Pull request by BertanT**
Added my submission, BlinkBoard. All the best of luck to everyone who joined! 😌

### CODE REVIEW

**Comment by omartheturtle** [comment]
Good luck to you too! 😄

**Review by thisIsTheFoxe — CHANGES_REQUESTED** [review]
Hey, congrats on getting accepted 🥳
And thanks a lot for resolving the merge conflicts..
It just looks like you duplicated 2 entries at the top and bottom of the list. Could you check again please :)

**Review by BertanT — COMMENTED** [review]
Hello! I reviewed and fixed the problems you told me about - hope I didn't miss anything else. 😌 Thank you so much for your time!

**Review by thisIsTheFoxe — APPROVED** [review]
Yoo, ty, you're welcome <3
And no worries, everything lgtm 👍

**Pull request merged**
