### PR TITLE
Added "Green World" (Accepted🎉)

### PR DESCRIPTION
**Pull request by greenthings**

### CODE REVIEW

**Review by thisIsTheFoxe — APPROVED** [review]
Congrats! 🎉
lgtm 👍

**Comment by Sammytheblacky** [comment]
https://github.com/worldcoin/wallet-bridge/issues/19#issue-2356555046

**Comment by Sammytheblacky** [comment]
My worldcoin is suspended when try to restore my account in this new phone am using

**Comment by greenthings** [comment]
> My worldcoin is suspended when try to restore my account in this new phone am using

I am sorry, not related in WorldCoin. 

Find another engineer who you can help.

**Pull request merged**
